(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (make-segment start end)
  (cons start end))
(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))
(define (average a b)
  (/ (+ a b) 2.0))
(define (midpoint-segment segment)
  (let* ((start (start-segment segment))
         (end (end-segment segment))
         (x-avg (average (x-point start) (x-point end)))
         (y-avg (average (y-point start) (y-point end))))
    (make-point x-avg y-avg)))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ", ")
  (display (y-point p))
  (display ")"))
(define (make-rect start end) ; Endpoints of the diagonal
  (cons start end))
(define (rect-length rect comp)
  (let ((a (comp (car rect)))
        (b (comp (cdr rect))))
    (abs (- a b))))
(define (hori-length rect)
  (rect-length rect x-point))
(define (vert-length rect)
  (rect-length rect y-point))
(define (perimeter rect)
  (let* ((a (hori-length rect))
         (b (vert-length rect)))
    (* 2.0 (+ a b))))
(define (area rect)
  (* (hori-length rect) (vert-length rect)))