(define (square x)
  (* x x))
(define (next-guess guess)
  (if (= 2 guess)
      3
      (+ 2 guess)))
(define (find-divisor n guess)
  (cond 
    ((= 0 (remainder n guess)) guess)
    ((> (square guess) n) n)
    (else (find-divisor n (next-guess guess)))))
(define (smallest-divisor n)
  (find-divisor n 2))
(define (prime? n)
  (= n (smallest-divisor n)))
